import { Worker, Employer, Attestation, Job, Badge, WorkType } from '@/types';

// Sample workers
export const sampleWorkers: Worker[] = [
  {
    id: 'w1',
    role: 'worker',
    name: 'Mary Wanjiku',
    phone: '+254712345678',
    location: 'Nairobi - Westlands',
    workTypes: ['nanny', 'cook'],
    bio: 'Caring and experienced nanny with 5 years working with children. I love cooking healthy meals for families.',
    yearsExperience: 5,
    isAvailable: true,
    createdAt: new Date('2023-01-15'),
    badges: [
      {
        id: 'b1',
        type: 'experienced',
        name: 'Experienced',
        description: '2+ years of verified experience',
        earnedAt: new Date('2024-06-01'),
        stellarTxHash: 'abc123...',
      },
      {
        id: 'b2',
        type: 'reliable',
        name: 'Reliable',
        description: '3+ confirmed work attestations',
        earnedAt: new Date('2024-08-15'),
        stellarTxHash: 'def456...',
      },
    ],
    attestations: [],
  },
  {
    id: 'w2',
    role: 'worker',
    name: 'Grace Atieno',
    phone: '+254723456789',
    location: 'Nairobi - Karen',
    workTypes: ['cleaner', 'houseManager'],
    bio: 'Professional house manager with experience in large households. Organized and detail-oriented.',
    yearsExperience: 8,
    isAvailable: true,
    createdAt: new Date('2022-06-20'),
    badges: [
      {
        id: 'b3',
        type: 'superstar',
        name: 'Superstar',
        description: '5+ verified work periods',
        earnedAt: new Date('2024-03-01'),
        stellarTxHash: 'ghi789...',
      },
      {
        id: 'b4',
        type: 'trusted',
        name: 'Trusted',
        description: 'Long-term employment',
        earnedAt: new Date('2024-01-15'),
        stellarTxHash: 'jkl012...',
      },
    ],
    attestations: [],
  },
];

export const sampleEmployer: Employer = {
  id: 'e1',
  role: 'employer',
  name: 'John Kamau',
  phone: '+254734567890',
  location: 'Nairobi - Lavington',
  householdName: 'The Kamau Household',
  createdAt: new Date('2023-03-01'),
};

export const sampleAttestations: Attestation[] = [
  {
    id: 'a1',
    workerId: 'w1',
    employerId: 'e1',
    employerName: 'The Kamau Household',
    workType: 'nanny',
    startDate: new Date('2023-06-01'),
    endDate: new Date('2024-05-31'),
    description: 'Excellent care for our two children. Very reliable and loving.',
    status: 'completed',
    stellarTxHash: 'GCEXAMPLE123...',
    createdAt: new Date('2024-06-01'),
    confirmedAt: new Date('2024-06-02'),
  },
  {
    id: 'a2',
    workerId: 'w1',
    employerId: 'e2',
    employerName: 'The Ochieng Family',
    workType: 'cook',
    startDate: new Date('2022-01-01'),
    endDate: new Date('2023-04-30'),
    description: 'Prepared delicious and healthy meals for our family of five.',
    status: 'completed',
    stellarTxHash: 'GCEXAMPLE456...',
    createdAt: new Date('2023-05-01'),
    confirmedAt: new Date('2023-05-02'),
  },
  {
    id: 'a3',
    workerId: 'w1',
    employerId: 'e3',
    employerName: 'Mrs. Njeri Muthoni',
    workType: 'nanny',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2025-01-31'),
    description: 'Currently caring for newborn. Highly professional.',
    status: 'pending',
    createdAt: new Date('2025-01-20'),
  },
];

export const sampleJobs: Job[] = [
  {
    id: 'j1',
    employerId: 'e1',
    employerName: 'The Kamau Household',
    title: 'Live-in Nanny for 2 Children',
    workType: 'nanny',
    description: 'Looking for an experienced nanny to care for our two children (ages 3 and 6). Must be patient, loving, and able to help with homework.',
    location: 'Nairobi - Lavington',
    salary: 'KES 25,000 - 35,000/month',
    isLiveIn: true,
    createdAt: new Date('2025-01-15'),
    status: 'open',
  },
  {
    id: 'j2',
    employerId: 'e2',
    employerName: 'The Ochieng Family',
    title: 'Part-time House Cleaner',
    workType: 'cleaner',
    description: 'Need a reliable cleaner for 3 days per week. Large home in Karen area.',
    location: 'Nairobi - Karen',
    salary: 'KES 1,500/day',
    isLiveIn: false,
    createdAt: new Date('2025-01-20'),
    status: 'open',
  },
  {
    id: 'j3',
    employerId: 'e3',
    employerName: 'Elderly Care Home',
    title: 'Caregiver for Elderly Lady',
    workType: 'caregiver',
    description: 'Seeking compassionate caregiver for 85-year-old grandmother. Experience with elderly care preferred.',
    location: 'Nairobi - Muthaiga',
    salary: 'KES 30,000/month',
    isLiveIn: true,
    createdAt: new Date('2025-01-18'),
    status: 'open',
  },
];
