import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Worker, GeneratedCV, WorkType } from '@/types';
import { PageLayout } from '@/components/layout/PageLayout';
import { Button } from '@/components/ui/button';
import { useApp } from '@/context/AppContext';
import { sampleAttestations } from '@/lib/sampleData';
import { generateCV } from '@/lib/cvGenerator';
import { WORK_TYPE_CONFIG } from '@/lib/constants';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { 
  FileText, 
  Download, 
  Share2, 
  Sparkles, 
  Briefcase,
  Award,
  CheckCircle,
  ArrowLeft,
  RefreshCw
} from 'lucide-react';
import { format } from 'date-fns';
import { toast } from 'sonner';

export default function GenerateCV() {
  const navigate = useNavigate();
  const { currentUser } = useApp();
  const worker = currentUser as Worker;
  
  const [isGenerating, setIsGenerating] = useState(true);
  const [cv, setCV] = useState<GeneratedCV | null>(null);
  const [tailorFor, setTailorFor] = useState<string>('');

  const attestations = worker ? sampleAttestations.filter(a => a.workerId === worker.id) : [];

  useEffect(() => {
    if (worker) {
      generateNewCV();
    }
  }, [worker]);

  const generateNewCV = (jobType?: string) => {
    setIsGenerating(true);
    
    // Simulate AI generation delay
    setTimeout(() => {
      if (worker) {
        const generatedCV = generateCV(worker, attestations, jobType);
        setCV(generatedCV);
      }
      setIsGenerating(false);
    }, 1500);
  };

  const handleTailorChange = (value: string) => {
    setTailorFor(value);
    if (value && value !== 'general') {
      generateNewCV(WORK_TYPE_CONFIG[value as WorkType]?.label);
    } else {
      generateNewCV();
    }
  };

  const handleDownload = async () => {
    if (!cv || !worker) return;
    
    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = 20;

    const addText = (text: string, size: number, style: 'normal' | 'bold' = 'normal', color: [number, number, number] = [30, 30, 30]) => {
      doc.setFontSize(size);
      doc.setFont('helvetica', style);
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text, contentWidth);
      if (y + lines.length * (size * 0.4) > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        y = 20;
      }
      doc.text(lines, margin, y);
      y += lines.length * (size * 0.45) + 2;
    };

    // Header
    addText(worker.name.toUpperCase(), 20, 'bold', [30, 80, 60]);
    addText(`${worker.location}  •  ${worker.phone}`, 10, 'normal', [100, 100, 100]);
    y += 4;

    // Line
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Summary
    addText('PROFESSIONAL SUMMARY', 12, 'bold', [30, 80, 60]);
    y += 1;
    addText(cv.summary, 10);
    y += 4;

    // Experience
    if (cv.experience.length > 0) {
      addText('WORK EXPERIENCE', 12, 'bold', [30, 80, 60]);
      y += 1;
      cv.experience.forEach(exp => {
        addText(`${exp.role}  —  ${exp.employer}`, 11, 'bold');
        addText(exp.period, 9, 'normal', [120, 120, 120]);
        addText(exp.description, 10);
        y += 2;
      });
      y += 2;
    }

    // Skills
    addText('SKILLS', 12, 'bold', [30, 80, 60]);
    y += 1;
    addText(cv.skills.map(s => `•  ${s}`).join('\n'), 10);
    y += 4;

    // Badges
    if (cv.badges.length > 0) {
      addText('CREDENTIALS & BADGES', 12, 'bold', [30, 80, 60]);
      y += 1;
      cv.badges.forEach(badge => {
        addText(`•  ${badge.name}: ${badge.description}`, 10);
      });
    }

    // Footer
    y += 8;
    addText(`Generated by Kazi Trust on ${format(cv.generatedAt, 'dd MMMM yyyy')}`, 8, 'normal', [150, 150, 150]);

    doc.save(`${worker.name.replace(/\s+/g, '_')}_CV.pdf`);
    toast.success('CV downloaded as PDF!');
  };

  const handleShare = async () => {
    if (!cv || !worker) return;
    
    const shareText = `Check out my professional CV from Kazi Trust!\n\n${cv.summary}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${worker.name} - Professional CV`,
          text: shareText,
        });
      } catch (err) {
        // User cancelled or share failed
        toast.info('Share cancelled');
      }
    } else {
      // Fallback: copy to clipboard
      await navigator.clipboard.writeText(shareText);
      toast.success('CV summary copied to clipboard!');
    }
  };

  if (!worker) {
    return (
      <PageLayout title="Generate CV">
        <div className="p-4 text-center text-muted-foreground">
          Please log in as a worker to generate your CV
        </div>
      </PageLayout>
    );
  }

  return (
    <PageLayout title="AI CV Generator" showBackButton>
      <div className="px-4 py-6 space-y-6">
        {/* Header */}
        <div className="text-center animate-fade-up">
          <div className="inline-flex items-center justify-center h-16 w-16 rounded-full bg-accent/15 mb-4">
            <Sparkles className="h-8 w-8 text-accent" />
          </div>
          <h2 className="text-xl font-display font-bold text-foreground">
            Your Professional CV
          </h2>
          <p className="text-muted-foreground mt-1">
            Generated from your verified work history
          </p>
        </div>

        {/* Tailor Selector */}
        <div className="animate-fade-up animation-delay-100">
          <label className="block text-sm font-medium text-foreground mb-2">
            Tailor CV for job type (optional)
          </label>
          <Select value={tailorFor} onValueChange={handleTailorChange}>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="General CV" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="general">General CV</SelectItem>
              {Object.entries(WORK_TYPE_CONFIG).map(([key, config]) => (
                <SelectItem key={key} value={key}>
                  {config.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Loading State */}
        {isGenerating && (
          <div className="bg-card rounded-2xl p-8 shadow-soft border border-border animate-fade-up">
            <div className="flex flex-col items-center justify-center space-y-4">
              <div className="relative">
                <div className="h-12 w-12 rounded-full border-4 border-primary/30 border-t-primary animate-spin" />
                <Sparkles className="h-5 w-5 text-primary absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
              </div>
              <p className="text-muted-foreground text-center">
                Creating your professional CV...
              </p>
            </div>
          </div>
        )}

        {/* CV Preview */}
        {!isGenerating && cv && (
          <div className="space-y-4 animate-fade-up animation-delay-200">
            {/* Summary Section */}
            <div className="bg-card rounded-2xl p-5 shadow-soft border border-border">
              <div className="flex items-center gap-2 mb-3">
                <FileText className="h-5 w-5 text-primary" />
                <h3 className="font-semibold text-foreground">Professional Summary</h3>
              </div>
              <p className="text-foreground leading-relaxed">{cv.summary}</p>
            </div>

            {/* Experience Section */}
            {cv.experience.length > 0 && (
              <div className="bg-card rounded-2xl p-5 shadow-soft border border-border">
                <div className="flex items-center gap-2 mb-4">
                  <Briefcase className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold text-foreground">Work Experience</h3>
                  <span className="ml-auto text-xs bg-success/15 text-success px-2 py-0.5 rounded-full font-medium">
                    Verified
                  </span>
                </div>
                <div className="space-y-4">
                  {cv.experience.map((exp, index) => (
                    <div key={index} className="border-l-2 border-primary/30 pl-4">
                      <div className="flex items-start justify-between">
                        <h4 className="font-medium text-foreground">{exp.role}</h4>
                        <CheckCircle className="h-4 w-4 text-success flex-shrink-0" />
                      </div>
                      <p className="text-sm text-muted-foreground">{exp.employer}</p>
                      <p className="text-xs text-muted-foreground mt-1">{exp.period}</p>
                      <p className="text-sm text-foreground mt-2">{exp.description}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Skills Section */}
            <div className="bg-card rounded-2xl p-5 shadow-soft border border-border">
              <div className="flex items-center gap-2 mb-3">
                <CheckCircle className="h-5 w-5 text-primary" />
                <h3 className="font-semibold text-foreground">Skills</h3>
              </div>
              <div className="flex flex-wrap gap-2">
                {cv.skills.map((skill, index) => (
                  <span
                    key={index}
                    className="px-3 py-1.5 bg-secondary text-secondary-foreground rounded-lg text-sm"
                  >
                    {skill}
                  </span>
                ))}
              </div>
            </div>

            {/* Badges Section */}
            {cv.badges.length > 0 && (
              <div className="bg-card rounded-2xl p-5 shadow-soft border border-border">
                <div className="flex items-center gap-2 mb-3">
                  <Award className="h-5 w-5 text-accent" />
                  <h3 className="font-semibold text-foreground">Credentials & Badges</h3>
                </div>
                <div className="space-y-2">
                  {cv.badges.map((badge, index) => (
                    <div key={index} className="flex items-center gap-3 p-2 bg-accent/10 rounded-lg">
                      <Award className="h-5 w-5 text-accent" />
                      <div>
                        <p className="font-medium text-foreground text-sm">{badge.name}</p>
                        <p className="text-xs text-muted-foreground">{badge.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Generated timestamp */}
            <p className="text-center text-xs text-muted-foreground">
              Generated on {format(cv.generatedAt, 'dd MMMM yyyy, HH:mm')}
            </p>
          </div>
        )}

        {/* Action Buttons */}
        {!isGenerating && cv && (
          <div className="space-y-3 animate-fade-up animation-delay-300">
            <Button 
              variant="warm" 
              size="xl" 
              className="w-full"
              onClick={handleDownload}
            >
              <Download className="h-5 w-5" />
              Download CV
            </Button>
            
            <div className="grid grid-cols-2 gap-3">
              <Button 
                variant="outline" 
                size="lg"
                onClick={handleShare}
              >
                <Share2 className="h-4 w-4" />
                Share
              </Button>
              <Button 
                variant="outline" 
                size="lg"
                onClick={() => generateNewCV(tailorFor !== 'general' ? WORK_TYPE_CONFIG[tailorFor as WorkType]?.label : undefined)}
              >
                <RefreshCw className="h-4 w-4" />
                Regenerate
              </Button>
            </div>
          </div>
        )}
      </div>
    </PageLayout>
  );
}
